version: '3.9'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-database
  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    ports:
      - 8080:8081
    networks:
      - mongo-database
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_db
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=29102002


  api:
    image: hoatran1002/cookingbackend:v1.0
    ports: 
      - 3000:3000
    networks:
      - mongo-database
    environment: 
      - MONGODB_URI=mongodb://mongo_db:27017/Cooking
    #   - PORT=3000
    #   - MONGODB_URI=mongodb://localhost:27017
    #   - DB_NAME=Cooking
    #   - NAME=Cooking_Backend
    links:
      - mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
networks:
  mongo-database:
    driver: bridge